---
locale: es
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":arrow_right:"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ":arrow_right:"
  checked: false
name: Primer ciclo 1
