---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
language: python3
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_passes
name: Interactivo Python3
