---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
language: python3
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_outputs
  query: 4 == x
  output: 'True'
name: Interactivo Python3
