---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: soy la correcta (posta)
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: no soy la correcta
  checked: false
name: New exercise
